name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-node-app .

      - name: Run tests
        run: |
          docker run --rm my-node-app npm test || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag my-node-app ramgopalhyndav/my-node-app:latest
          docker push ramgopalhyndav/my-node-app:latest

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to DigitalOcean
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no root@139.59.47.63 << 'EOF'
            # Pull the latest Docker image
            docker pull ramgopalhyndav/my-node-app:latest
            
            # Stop and remove existing containers based on the image
            CONTAINERS=$(docker ps -q --filter "ancestor=ramgopalhyndav/my-node-app:latest")
            if [ -n "$CONTAINERS" ]; then
              docker stop $CONTAINERS
              docker rm $CONTAINERS
            fi
            
            # Remove old containers if any
            OLD_CONTAINERS=$(docker ps -a -q --filter "ancestor=ramgopalhyndav/my-node-app:latest")
            if [ -n "$OLD_CONTAINERS" ]; then
              docker rm $OLD_CONTAINERS
            fi
            
            # Check if port 80 is in use and use an alternative port if necessary
            if docker ps --format '{{.Ports}}' | grep -q '80->'; then
              PORT=8080
            else
              PORT=80
            fi
            
            # Run the new container
            docker run -d -p $PORT:3000 ramgopalhyndav/my-node-app:latest
          EOF
